[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["experiments*"]

[project]
name = "sidewire"
version = "0.1.5"
description = "Lightweight MQTT-based secure P2P messaging layer"
readme = "README.md"
requires-python = ">=3.5"
authors = [
    {name="Matthew Roberts", email="matthew@roberts.pm"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "aionetiface",
    "ecdsa"
]